language: node_js
node_js:
- "6.4.0"

before_script:
    - sudo ln -s $(which node) /bin
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /tmp/cc-test-reporter
    - chmod +x /tmp/cc-test-reporter

script:
    - /tmp/cc-test-reporter before-build
    - npm test
    - npm run-script coverage

after_success:
    - /tmp/cc-test-reporter after-build
    - bash ./deploy.sh

